Merge info into existing connection files if they already exist
ipython/ipykernel pull request #1133
Opened 2023-07-13 04:45 UTC by jasongrout

This lets a connection file specify a port as 0 and then be updated when ipykernel picks a port

2023-07-13 12:13 UTC, jasongrout-db commented
In https://github.com/ipython/ipykernel/pull/1127, ipykernel was changed to not overwrite a kernel connection file when it already exists. This broke a pattern we used at Databricks to address the issues from https://github.com/jupyter/jupyter_client/issues/487 and https://github.com/jupyter/enhancement-proposals/pull/66 (i.e., [JEP 66](https://github.com/jupyter/enhancement-proposals/blob/master/66-jupyter-handshaking/jupyter-handshaking.md)). Our pattern was this:

1. The kernel client writes a connection file like the following, where all the port numbers are zero:
   ```json
    {
      "shell_port": 0,
      "iopub_port": 0,
      "stdin_port": 0,
      "control_port": 0,
      "hb_port": 0,
      "ip": "127.0.0.1",
      "key": "53a0b8b4-e6272129eb8f4602affee828",
      "transport": "tcp",
      "signature_scheme": "hmac-sha256",
      "kernel_name": ""
    }
   ```
2. ipykernel is started, pointing at that connection file.
3. ipykernel/zmq picks random ports for each of the channels
4. ipykernel (before https://github.com/ipython/ipykernel/pull/1127) overwrites the connection file with the correct port numbers it actually connected to
5. We read the connection file to see what ports the client needs to use to communicate with ipykernel.

Since https://github.com/ipython/ipykernel/pull/1127, the connection file is not updated with the actual ports ipykernel is using.

2023-07-20 19:29 UTC, jasongrout commented
@blink1073 - pinging you for review, since you also reviewed #1127. I'm not sure if this usecase of setting the port number to 0 and having the kernel rewrite the connection file with the actual port was considered in the original discussion on #1127.

We discussed this briefly in the server/kernels meeting today, and we had a generally positive reaction from people there today, and no objections to the idea of updating the connection file.

2023-07-20 19:43 UTC, jasongrout commented
Ping also @fecet, the original author of #1127. This PR implements your idea at https://github.com/ipython/ipykernel/pull/1127#issuecomment-1600761391:

> ... Or can we just read the kernel file if exists, and only update the difference? ....

2023-07-20 19:55 UTC, jasongrout commented
The tests_check CI test is failing because the prerelease test timed out. The prerelease test timed out 99% of the way through, so perhaps it is just at the borderline of the timeout (i.e., it looks to me like this failure is not particular to this PR).

2023-07-20 20:16 UTC, JohanMabille commented
Now that [JEP 66](https://github.com/jupyter/enhancement-proposals/blob/master/66-jupyter-handshaking/jupyter-handshaking.md) has been approved, will you still need the ability to overwrite the connection file when ipykernel implements the handshake pattern? This latter seems more efficient to me since it does not require polling the file system.

2023-07-20 20:36 UTC, SylvainCorlay requested changes
This PR changes ipykernel's behavior with respect to the mechanism for port selection. 
JEP 66 just went through, addressing this very issue. Could we work together on implementing the JEP rather than adding a special workaround in ipykernel?

2023-07-21 00:04 UTC, fecet commented
> Ping also @fecet, the original author of #1127. This PR implements your idea at https://github.com/ipython/ipykernel/pull/1127#issuecomment-1600761391:
> 
> > ... Or can we just read the kernel file if exists, and only update the difference? ....

great to hear that！

2023-07-21 05:05 UTC, jasongrout commented
> Now that [JEP 66](https://github.com/jupyter/enhancement-proposals/blob/master/66-jupyter-handshaking/jupyter-handshaking.md) has been approved, will you still need the ability to overwrite the connection file when ipykernel implements the handshake pattern? This latter seems more efficient to me since it does not require to poll the file system.

I don't know - but that is a hypothetical at this point since it isn't implemented, and the change in 6.23.3 (accidentally) broke long-standing behavior and is breaking actual systems in use right now that rely on that behavior.

> This PR changes ipykernel's behavior with respect to the mechanism for port selection.
> JEP 66 just went through, addressing this very issue. Could we work together on implementing the JEP rather than adding a special workaround in ipykernel?

The way I see it, there was an accidental regression introduced in #1127, released in a patch release, that changed long-standing behavior that people rely on right now in ipykernel. This is breaking systems that rely on ipykernel right now. We should have brought this regression to @fecet's attention in #1127, but regardless, here we are.

This PR does not change ipykernel's behavior, rather it restores long-standing behavior to what it was before the regression. Of course, another route would be to revert #1127, but I think this PR preserves the intent of #1127 without this regression, and happily aligns with one of @fecet's original suggestions for #1127.

I think once we've resolved this regression, we can have a discussion about whether this port 0 behavior should be superseded by JEP 66's ideas, but of course that succession should happen deliberately, with a period for migration, only after JEP 66 has been implemented.

2023-07-21 07:06 UTC, SylvainCorlay commented
Let's discuss how we can resolve the issue caused by the change of behavior in https://github.com/ipython/ipykernel/pull/1127.

> I think once we've resolved this regression, we can have a discussion about whether this port 0 behavior should be superseded by JEP 66's ideas, but of course that succession should happen deliberately, with a period for migration, only after JEP 66 has been implemented.

The idea of not passing ports and polling the file system to wait for the info to be populated by the kernel was addressed in the discussion about the JEP.

2023-07-21 10:45 UTC, jasongrout commented
> Let's discuss how we can resolve the issue caused by the change of behavior in #1127.

Thank you. I agree - I think *this* PR discussion should be about fixing the regression in behavior introduced in #1127. Here are, for example, two paths forward:

1. Revert #1127 (if this is going to be a long discussion blocking merging of this PR, I'd advocate for reverting to unbreak things in the short term)
2. Merge this PR, which achieves the aims of #1127 while preserving long-standing ipykernel behavior

I prefer merging this PR, as it builds on #1127 (which did solve an important issue). Which do you prefer, or do you see another path forward that fixes the behavior change in #1127 in the short term?

> The idea of not passing ports and polling the file system to wait for the info to be populated by the kernel was addressed in the discussion about the JEP.

Great! I think there are other places to discuss JEP 66 - let's not rehash a JEP 66 discussion here.

2023-07-21 11:42 UTC, blink1073 commented
I'm afk until next Monday, feel free to do whatever you all think is best with this PR.

2023-07-21 15:49 UTC, ccordoba12 commented
> The way I see it, there was an accidental regression introduced in https://github.com/ipython/ipykernel/pull/1127, released in a patch release, that changed long-standing behavior that people rely on right now in ipykernel. This is breaking systems that rely on ipykernel right now. We should have brought this regression to @fecet's attention in https://github.com/ipython/ipykernel/pull/1127, but hey, systems are complicated, and it's not clear anyone recognized this regression at the time, so here we are.
>
> This PR does not change ipykernel's behavior, rather it restores long-standing behavior to what it was before the regression

Given this analysis of the situation that Jason provided, I agree that we should either merge this PR or revert #1127 (preferable?) and release a new bugfix version to restore the previous behavior.

Just my 2 cents.

2023-07-21 18:30 UTC, fecet commented
If https://github.com/ipython/ipykernel/pull/1127 be revoked I hope this https://github.com/jupyter/notebook/issues/6936 can also be considered.

2023-07-25 16:11 UTC, blink1073 commented
I'm going to merge this to fix the current bug, we can address JEP 66 as a follow-up.

2023-07-25 16:11 UTC, merged

2023-07-26 12:26 UTC, SylvainCorlay commented
I have a reservation with respect to the special casing of the port number "0" to signal that ports have to be chosen. (this behavior is not really part of the protocol. If this fixes your scenario, I guess this is fine as a temporary fix.